"""add_dismissal_tracking_to_memberships

Revision ID: b4d54185eb42
Revises: 121e5ef7df79
Create Date: 2025-12-16 23:03:46.719295+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d54185eb42'
down_revision: Union[str, None] = '121e5ef7df79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_memberships', sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('club_memberships', sa.Column('dismissed_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_club_memberships_dismissed_by_id'), 'club_memberships', ['dismissed_by_id'], unique=False)
    op.create_foreign_key(None, 'club_memberships', 'user_accounts', ['dismissed_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'club_memberships', type_='foreignkey')
    op.drop_index(op.f('ix_club_memberships_dismissed_by_id'), table_name='club_memberships')
    op.drop_column('club_memberships', 'dismissed_by_id')
    op.drop_column('club_memberships', 'dismissed_at')
    # ### end Alembic commands ###
