"""add document_url to organizer_rules

Revision ID: 0f8de3b121c4
Revises: 4ebe1a4189a1
Create Date: 2025-12-24 17:02:41.354980+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8de3b121c4'
down_revision: Union[str, None] = '4ebe1a4189a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizer_rules', sa.Column('document_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizer_rules', 'document_url')
    # ### end Alembic commands ###
