"""add_scoring_method_and_event_settings

Revision ID: cb4d93ed7d46
Revises: cf32c742b282
Create Date: 2025-12-06 19:12:31.228255+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4d93ed7d46'
down_revision: Union[str, None] = 'cf32c742b282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('top_x_overall', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('has_bonus_points', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('scoring_configs', sa.Column('scoring_method', sa.String(length=50), server_default='top_x_by_species', nullable=False))
    op.add_column('scoring_configs', sa.Column('default_top_x', sa.Integer(), server_default='10', nullable=False))
    op.add_column('scoring_configs', sa.Column('default_catch_slots', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scoring_configs', 'default_catch_slots')
    op.drop_column('scoring_configs', 'default_top_x')
    op.drop_column('scoring_configs', 'scoring_method')
    op.drop_column('events', 'has_bonus_points')
    op.drop_column('events', 'top_x_overall')
    # ### end Alembic commands ###
