"""add_location_to_clubs

Revision ID: 121e5ef7df79
Revises: 20251216_000002
Create Date: 2025-12-16 22:32:29.737712+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121e5ef7df79'
down_revision: Union[str, None] = '20251216_000002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('clubs', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_clubs_city_id'), 'clubs', ['city_id'], unique=False)
    op.create_index(op.f('ix_clubs_country_id'), 'clubs', ['country_id'], unique=False)
    op.create_foreign_key(None, 'clubs', 'countries', ['country_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'clubs', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.alter_column('user_accounts', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_accounts', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'clubs', type_='foreignkey')
    op.drop_constraint(None, 'clubs', type_='foreignkey')
    op.drop_index(op.f('ix_clubs_country_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_city_id'), table_name='clubs')
    op.drop_column('clubs', 'city_id')
    op.drop_column('clubs', 'country_id')
    # ### end Alembic commands ###
