"""add_event_soft_delete_fields

Revision ID: 2bd77570179e
Revises: 7199bd8e6d0b
Create Date: 2025-12-20 20:07:03.176796+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd77570179e'
down_revision: Union[str, None] = '7199bd8e6d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('events', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_events_is_deleted'), 'events', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'events', 'user_accounts', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_is_deleted'), table_name='events')
    op.drop_column('events', 'deleted_by_id')
    op.drop_column('events', 'deleted_at')
    op.drop_column('events', 'is_deleted')
    # ### end Alembic commands ###
