"""change_prize_value_to_string

Revision ID: 044d655df871
Revises: 20251222_000003
Create Date: 2025-12-22 20:33:47.257738+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044d655df871'
down_revision: Union[str, None] = '20251222_000003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use USING clause to convert existing float values to text
    op.alter_column('event_prizes', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=200),
               existing_nullable=True,
               postgresql_using='value::text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_prizes', 'value',
               existing_type=sa.String(length=200),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
