"""add_event_media_constraints

Revision ID: 28ac2eea2240
Revises: 2bd77570179e
Create Date: 2025-12-21 11:38:18.003912+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ac2eea2240'
down_revision: Union[str, None] = '2bd77570179e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add with server_default for existing rows, then remove default
    op.add_column('events', sa.Column('allow_gallery_upload', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('events', sa.Column('allowed_media_type', sa.String(length=20), nullable=False, server_default='both'))
    op.add_column('events', sa.Column('max_video_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'max_video_duration')
    op.drop_column('events', 'allowed_media_type')
    op.drop_column('events', 'allow_gallery_upload')
    # ### end Alembic commands ###
