"""add_tsf_sector_validators

Revision ID: c4ed2752cf78
Revises: 20251229_100002
Create Date: 2025-12-29 11:35:14.539474+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ed2752cf78'
down_revision: Union[str, None] = '20251229_100002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tsf_leg_positions', sa.Column('validated_by_id', sa.Integer(), nullable=True))
    op.add_column('tsf_leg_positions', sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'tsf_leg_positions', 'user_accounts', ['validated_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tsf_leg_positions', type_='foreignkey')
    op.drop_column('tsf_leg_positions', 'validated_at')
    op.drop_column('tsf_leg_positions', 'validated_by_id')
    # ### end Alembic commands ###
