"""Add notify_event_catches to notification preferences

Revision ID: 7199bd8e6d0b
Revises: 1917d88a4680
Create Date: 2025-12-20 19:44:46.499307+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7199bd8e6d0b'
down_revision: Union[str, None] = '1917d88a4680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notification_preferences', sa.Column('notify_event_catches', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_notification_preferences', 'notify_event_catches')
    # ### end Alembic commands ###
