"""add_completed_at_to_events

Revision ID: d91bbd3bf801
Revises: 9b4d6f8e0a23
Create Date: 2025-12-25 12:54:04.454933+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91bbd3bf801'
down_revision: Union[str, None] = '9b4d6f8e0a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'completed_at')
    # ### end Alembic commands ###
