"""add_fish_name_translations

Revision ID: 86b8cb4df4cb
Revises: 20251223_000005
Create Date: 2025-12-24 08:48:00.787950+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b8cb4df4cb'
down_revision: Union[str, None] = '20251223_000005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish', sa.Column('name_en', sa.String(length=100), nullable=True))
    op.add_column('fish', sa.Column('name_ro', sa.String(length=100), nullable=True))
    op.drop_index('ix_pro_grants_expires_at', table_name='pro_grants')
    op.drop_constraint('pro_settings_key_key', 'pro_settings', type_='unique')
    op.create_index(op.f('ix_pro_settings_id'), 'pro_settings', ['id'], unique=False)
    op.drop_constraint('pro_subscriptions_stripe_subscription_id_key', 'pro_subscriptions', type_='unique')
    op.create_index(op.f('ix_pro_subscriptions_id'), 'pro_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_pro_subscriptions_stripe_subscription_id'), 'pro_subscriptions', ['stripe_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pro_subscriptions_stripe_subscription_id'), table_name='pro_subscriptions')
    op.drop_index(op.f('ix_pro_subscriptions_id'), table_name='pro_subscriptions')
    op.create_unique_constraint('pro_subscriptions_stripe_subscription_id_key', 'pro_subscriptions', ['stripe_subscription_id'])
    op.drop_index(op.f('ix_pro_settings_id'), table_name='pro_settings')
    op.create_unique_constraint('pro_settings_key_key', 'pro_settings', ['key'])
    op.create_index('ix_pro_grants_expires_at', 'pro_grants', ['expires_at'], unique=False)
    op.drop_column('fish', 'name_ro')
    op.drop_column('fish', 'name_en')
    # ### end Alembic commands ###
