"""Add notification preferences and device tokens

Revision ID: 1917d88a4680
Revises: c7b94352e568
Create Date: 2025-12-20 19:37:44.828017+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1917d88a4680'
down_revision: Union[str, None] = 'c7b94352e568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catches_revalidated_by_id', table_name='catches')
    op.drop_index('idx_events_rule', table_name='events')
    op.create_index(op.f('ix_events_rule_id'), 'events', ['rule_id'], unique=False)
    op.drop_constraint('uq_fish_slug', 'fish', type_='unique')
    op.drop_index('ix_fish_slug', table_name='fish')
    op.create_index(op.f('ix_fish_slug'), 'fish', ['slug'], unique=True)
    op.drop_index('uq_sponsors_name_owner', table_name='sponsors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_sponsors_name_owner', 'sponsors', ['name', sa.text('COALESCE(owner_id, 0)')], unique=True)
    op.drop_index(op.f('ix_fish_slug'), table_name='fish')
    op.create_index('ix_fish_slug', 'fish', ['slug'], unique=False)
    op.create_unique_constraint('uq_fish_slug', 'fish', ['slug'])
    op.drop_index(op.f('ix_events_rule_id'), table_name='events')
    op.create_index('idx_events_rule', 'events', ['rule_id'], unique=False)
    op.create_index('ix_catches_revalidated_by_id', 'catches', ['revalidated_by_id'], unique=False)
    # ### end Alembic commands ###
