"""add_gender_to_user_profile

Revision ID: 4ebe1a4189a1
Revises: 2906b68d73fe
Create Date: 2025-12-24 13:22:28.310818+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebe1a4189a1'
down_revision: Union[str, None] = '2906b68d73fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('gender', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'gender')
    # ### end Alembic commands ###
