"""add_minigame_scores

Revision ID: 9a373e034ff0
Revises: 20251231_100001
Create Date: 2026-01-01 10:22:23.048773+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a373e034ff0'
down_revision: Union[str, None] = '20251231_100001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minigame_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('fish_caught', sa.Text(), nullable=True, comment='JSON array of fish caught during session'),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='Game session duration in seconds'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_minigame_scores_score', 'minigame_scores', ['score'], unique=False)
    op.create_index('ix_minigame_scores_user_id', 'minigame_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_minigame_scores_user_id', table_name='minigame_scores')
    op.drop_index('ix_minigame_scores_score', table_name='minigame_scores')
    op.drop_table('minigame_scores')
    # ### end Alembic commands ###
